name: CI for Bun Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Bun
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Step 3: Install dependencies
      - name: Install dependencies
        run: bun install

      # Step 4: Run linter
      - name: Run linter
        run: bun run lint:check

      # Step 5: Run tests
      - name: Run tests
        run: bun test
